name: CI - Train Model

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r MLProject/requirements.txt

    - name: Run MLflow project
      run: |
        cd MLProject
        export MLFLOW_TRACKING_URI=file:./mlruns
        mlflow run . --env-manager=local

    - name: Debug folder saved_models
      run: |
        echo "Isi folder MLProject/saved_models:"
        ls -R MLProject/saved_models || echo "❌ Folder tidak ditemukan"

    - name: Debug token access
      run: echo "${{ secrets.GH_TOKEN }}" | wc -c

    - name: Commit & Push trained models
      run: |
        cd MLProject
        git config user.name github-actions
        git config user.email github-actions@github.com

        # Ganti remote origin agar pakai token GH_TOKEN milikmu
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}

        git add -f saved_models || true
        git diff --cached --quiet || (
          echo "Commit & push model hasil training..."
          git commit -m "Add trained models from CI run"
          git push origin main
        )

