name: Train Model Automatically

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/train_model.yml'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install mlflow

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --no-conda

    - name: Push saved models to GitHub
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add MLProject/saved_models
        git commit -m "Add trained models from CI run"
        git push origin main