name: CI - Train and Deploy Model

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r MLProject/requirements.txt

    - name: Run MLflow project
      run: |
        cd MLProject
        export MLFLOW_TRACKING_URI=file:./mlruns
        mlflow run . --env-manager=local

    - name: Get latest MLflow run_id
      id: get_run_id
      run: |
        cd MLProject
        export MLFLOW_TRACKING_URI=file:./mlruns
        run_id=$(ls -1t ./mlruns/0 | grep -E '^[a-f0-9]{32}$' | head -n 1)
        echo "MLFLOW_RUN_ID=$run_id" >> $GITHUB_ENV
        echo "Latest run_id: $run_id"

    - name: Build Docker image from model
      run: |
        cd MLProject
        export MLFLOW_TRACKING_URI=file:./mlruns
        mlflow models build-docker -m "runs:/${{ env.MLFLOW_RUN_ID }}/model" -n personality-image

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push Docker image
      run: |
        docker tag personality-image ${{ secrets.DOCKER_USERNAME }}/personality-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/personality-image:latest

    - name: Log out of Docker
      run: docker logout
    - name: Debug folder saved_models
      run: |
        echo "Isi folder MLProject/saved_models:"
        ls -R MLProject/saved_models || echo "❌ Folder tidak ditemukan"

    - name: Debug token access
      run: echo "${{ secrets.GH_TOKEN }}" | wc -c

    - name: Commit & Push trained models
      run: |
        cd MLProject
        git config user.name github-actions
        git config user.email github-actions@github.com

        
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

        git add -f saved_models || true
        git diff --cached --quiet || (
          echo "Commit & push model hasil training..."
          git commit -m "Add trained models from CI run"
          git push origin main
        )


