name: Train Model Automatically

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/train_model.yml'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install mlflow
        conda --version
        conda create -n mlflow-env -y python=3.10
        conda install -n mlflow-env -y pip
        conda run -n mlflow-env pip install -r MLProject/requirements.txt

    - name: Run MLflow Project using conda run
      run: |
        cd MLProject
        MLFLOW_RUN_SUBCOMMAND="conda run -n mlflow-env python" mlflow run . --env-manager=local
