name: Train Model Automatically

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/train_model.yml'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MLflow
      run: pip install mlflow

    - name: Run MLflow Project
      run: mlflow run ./MLProject
